name: Update to Public DB

on:
  schedule:
    - cron : '1 * * * *'
  workflow_dispatch: #manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code:
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo TALENTDB_DB_URL=${{ secrets.TALENTDB_DB_URL }} > .env 
        echo TALENTDB_DB_SHEETNAME=${{ secrets.TALENTDB_DB_SHEETNAME }} >> .env 
        echo TALENTDB_DB_USER=${{ secrets.TALENTDB_DB_USER }} >> .env 
        echo TALENTDB_DB_PASS=${{ secrets.TALENTDB_DB_PASS }} >> .env 
        echo TALENTDB_NOTION_APIKEY=${{ secrets.TALENTDB_NOTION_APIKEY }} >> .env 
        echo TALENTDB_NOTION_APIURL=${{ secrets.TALENTDB_NOTION_APIURL }} >> .env 
        echo TALENTDB_NOTION_DB_ID=${{ secrets.TALENTDB_PUBLICDB }} >> .env
    - name: Execute
      run: python main.py
